version: '24.0.2'
services:
  dev-db:
    image: postgres:15
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: 'daniel_h'
      POSTGRES_PASSWORD: 'aRealBadIdea4774!'
      POSTGRES_DB: nest
    networks:
      - danielsnet
  test-db:
    image: postgres:15
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: 'daniel_h'
      POSTGRES_PASSWORD: 'aRealBadIdea4774!'
      POSTGRES_DB: nest
    networks:
      - danielsnet
networks:
  danielsnet:
